Hamming needs knowledge of Conditionals
exercism/jq pull request #163
Opened 2023-04-08 21:01 UTC by glennj

I had a mentoring session where the student submitted Hamming before doing Conditionals in the syllabus. They correctly pointed out that it's impossible to complete without knowing `if`.

2023-04-08 21:25 UTC, IsaacG requested changes

2023-04-08 21:25 UTC, IsaacG commented on config.json
> +		  "conditionals"
`s/\t/<space><space><space><space>/`

2023-04-09 02:17 UTC, glennj commented on config.json
> +		  "conditionals"
oops. vim-go sets expandtab off.

2023-04-09 04:11 UTC, IsaacG approved these changes

2023-04-09 04:11 UTC, merged